version: "3.7"
services:
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    volumes:
      - ./auth_service/app:/app
    networks:
      - mynetwork

  main_service:
    build: ./main_service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./main_service/app:/app
    networks:
      - mynetwork


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ connection
      - "15672:15672" # RabbitMQ Management Console
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
